### ISSUE TITLE
Video containing sentry trigger doesn't run on folder open

### ISSUE THREAD

**Issue by Benn** [NateMccomb/TeslaCamViewer-legacy#18] opened 2019-10-05 22:04 UTC
When I open a folder of Sentry footage, the video is loaded on the trigger, all 3 videos are frozen. The cursor goes forward, but video is still.
If I click to another clip and come back to the one containing the trigger, it runs great.
I'm using Windows 10 Pro.
Thanks

**Comment by Kumasasa** [comment] 2019-10-06 00:35
This is caused by the bug in the Tesla Firmware since V9 2019.24.4
Tesla encodes the video files with a non-zero starting time which causes that you cannot step/jump in the video files.
This is a duplicate of #11

**Comment by NateMccomb** [comment] 2019-10-24 07:08
@Benn, 
@Kumasasa is correct that it's a bug from FW 2019.24.4 but if you right click on a folder or parent folder and click "Fix Tesla Freezing Bug" or "Re-Encode Files" will fix this issue along with a few other minor issues sometimes found TeslaCam files.

**Closed as completed by NateMccomb** 2019-10-24 07:08 UTC
