### ISSUE TITLE
Video stuttering

### ISSUE THREAD

**Issue by DrPippin** [NateMccomb/TeslaCamViewer-legacy#7] opened 2019-06-27 00:38 UTC
Video stuttering when previewing seems worse in 2019.26.0.0, and in fact outputted videos now are also stuttering.  CPU usage, etc. all remains minimal while previewing and while saving.  I ran the installer for 2019.26.0.0 to overwrite the previous version.

Here is a zip file containing the 3 camera angles and the outputted video I just tried making that demonstrate this behavior on my machine: https://drive.google.com/open?id=1pN8Ye8no-67G5x-uDysvDpMhGH39u7gm

**Comment by NateMccomb** [comment] 2019-06-27 07:41
This is very helpful and thanks for sending me these files. I found a few bugs but also have a few questions for troubleshooting. 
* Are you previewing your TeslaCam files directly from you USB drive or have you transferred them to your local hard drive? If you haven't tried transferring them locally, give it a try and see if it help with basic preview playback. Maybe your USB drive is a USB 2.0(black) drive (or plugged in a 2.0 black port) and not USB 3.0(blue). I currently use a Corsair Flash Survivor Stealth 64GB USB 3.0 thumb drives for TeslaCam.
* Did you have multiple clips selected when you went to export the video? I see the start timecode(14:16:47) of the "Outputted video.mp4" does not match the time(14-13-05) of files you sent, I ask because it's off by 2 min. 
* Also did you change the render speed to something other then 1x, because I did just find a bug when selecting any other playback speed or when the In/Out markers have been changed. 

I also found when I tried exporting your clips, that the exported video is being saved at half the frame rate(15.5 instead of 36.018 FPS) and may be part of the reason it looks like it's stuttering. I also see that your "Outputted video.mp4" was only saved at 5.680FPS and defiantly explains the stuttering and why I question the export playback speed.
Give me a few days to see what I can figure out with these bugs and I'll post an updated version ASAP.

**Comment by DrPippin** [comment] 2019-06-28 23:13
1) I've tried previewing from the USB, from a network drive, and from my local hard drive.  No change in behavior with any of the file locations.

2) Only one clip was selected for export.  When exporting I did change the start and stop times for the file, but only delaying the start ~15 seconds and the end by ~2 seconds (or something like that, very minor changes).

3) I didn't change the render speed.

The FPS you listed is really strange and I hadn't even thought to look at that.  Please let me know what I can do to help track down the issue.

**Comment by NateMccomb** [comment] 2019-06-30 05:05
Try Version 2019.26.6.0 and see if the rendered video looks any better. 
Also try opening all three cameras at the same time with "Media Player Classic", do a search from your Start button and see how well the videos playback. 
If Windows MPC not already installed, try downloading or Google ["K-Lite Codec Pack standard"](https://www.codecguide.com/download_k-lite_codec_pack_standard.htm) and not only will it install Windows Media Player Classic but also some other useful codecs that might help with playback.

**Comment by DrPippin** [comment] 2019-07-02 03:26
I read your first line and got excited so started experimenting before seeing your suggestion to install the codec pack, so all the shared files and screenshots are before installing the codec pack, but I went back and checked after installing the codek pack and nothing was different.  In the linked folder, there is a screenshot that shows the output log during the rendering process (I assume "drop" refers to dropped frames?).  There are also two folders ("1" and "2").

Folder 1 shows no stuttering in the outputted file, however the previews did stutter in TeslaCam Viewer with the included camera angles.

Folder 2 has a few different things relevant in it - 9 TeslaCam angles from 3 video segments, 2 outputted videos, and 4 screenshots.  The previews in TeslaCam stuttered with all these videos, but outputting had different outcomes.  There was one repeater video that was corrupted, and if I selected all 9 video angles (including the corrupted one) my options for the output video layout was limited as though I only had 2 video files for all video segments (I think you'll be able to figure out what I mean comparing the screenshots).  The outputted file stuttered when just outputting the forward camera from selecting all 9 camera angles from the 3 video segments, but it didn't stutter when outputting 3 camera views for 2 video segments (skipping the segment that had a corrupted repeater video).

All camera angles (straight from the USB drive) played perfectly without stuttering in Media Player Classic, except the corrupted file.

https://drive.google.com/open?id=13j7oxyCrXpvOKpEhAXgY1tIp5zkxLpvY

**Comment by NateMccomb** [comment] 2019-07-02 14:39
I haven't looked into the drop frames that FFmpeg reports yet but have noticed it for a while.

Folder 1 Issues:
---
* The front camera looks perfect like it always does. This is the most reliable camera that is recorded and always has the best quality videos unlike the repeater cameras.
* The Left Repeater camera also looks good but your Right Repeater has the Tesla video glitch. This is something I've notice with the side cameras all the time and is out of my control. This is how the side camera was recorded and not related to the viewers ability to play it. 

Is the Right Repeater camera the one you are describing as having the stuttering issues or is there something else I'm not seeing?  

Folder 2 Issues:
---
* I didn't see any screen shots included in folder 2
* The issue you're having with limited rendering views is due to the file missing or being corrupted. FFmpeg will crash if given a video file with 0 bytes as in your case 2019-07-01_17-33-22-right_repeater.mp4. This was a new feature added in a recent update to prevent rendering issues, FFmpeg can't re-encode something that doesn't exist so the viewer will eliminate the view options that have files missing or with 0 bytes. 
* Your "Exported with 3 selected.mp4" was encoded at 7.560 FPS instead of 36.00 FPS and has the same issue you mentioned a week ago with stuttering.

The Fix:
---
I was dynamically trying to figure out the FPS when the 'Render' button was selected but this seems to be the cause of the issue as the FPS fluctuates a bit during playback. All rendered files will now be saved at a fixed 36 Frames Per Second to match original TeslaCam FPS and this has also eliminated the drop frames we were seeing during the rendering process for FFmpeg. I'll revisit this if Tesla decides to start recording TeslaCam clips at 60FPS.
[Standalone-TeslaCamViewer-2019.27.2.0.zip](https://github.com/NateMccomb/TeslaCamViewer/files/3350503/Standalone-TeslaCamViewer-2019.27.2.0.zip)
[Installer-TeslaCamViewer-2019.27.2.0.zip](https://github.com/NateMccomb/TeslaCamViewer/files/3350504/Installer-TeslaCamViewer-2019.27.2.0.zip)

**Comment by DrPippin** [comment] 2019-07-04 17:10
Running 2019.27.4.1:

Folder 1 - The outputted file played perfectly.  But when previewing the videos in TeslaCam Viewer the previews were stuttering/dropping frames.  I did a screen capture to show on another set of files: https://drive.google.com/open?id=1l7-ITRUcL8f4CmDvi47Z60G80Z6CiGRV As you can see the stuttering starts pretty quickly, then when I jump ahead in the preview the video plays smoothly for a few seconds before it begins to stutter again.  The outputted file played perfectly despite the previews stuttering.

Folder 2 - Sorry, I re-uploaded the screenshots to that folder.  But yes, you exactly nailed what I was mentioning.  What I was hoping would be if there were a way to still encode the selected video files and just put a black box in place of the corrupted video.  Reason I can see this being beneficial would be if you have a 3 minute clip you want to render with all available camera angles, but one of the 9 individual video files is corrupted.  Currently you could only get 2 camera angles for the entire 3 minute clip even though only 1 minute of the clip is hampered by a corrupted file (I hope that makes sense).

Your fix of locking to 36 FPS has worked for all the outputted video files I have experimented with so far.  Would it be possible to do that same thing for the previewed videos?

**Comment by NateMccomb** [comment] 2019-07-09 04:03
I have no way of adjusting the resolution within the media player I'm using but I have a few things for you to try. The first would be to try it on another PC and see if your having the same issues. If this is not a option then try these two thing and let me know what you find out. 

Open 3 instances of "Windows Media Player Classic" like seen here:
![image](https://user-images.githubusercontent.com/9289783/60858143-28724d00-a1db-11e9-8dc8-190fce372705.png)
Now open one of the camera files that you've seen having issues in each of the players and see how they playback with all three playing. 

If there is no issues then try creating 3 folders and add the affected video files to each folder as followed. One file to the first folder, 2 files to the 2nd, 3 files to the 3rd and then check how each folder plays back in TeslaCam Viewer.

**Closed as completed** 2019-10-24 07:24 UTC
